---
swagger: '2.0'
info:
  version: '1.0'
  title: HelloDBP
host: MC2029402218:5555
basePath: /restv2
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /HelloDBP/thing:
    get:
      description: Returns list of all things.
      operationId: listThings
      parameters: []
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Things'
        401:
          description: Access Denied
    post:
      description: Creates a new thing.
      operationId: createThing
      parameters:
      - name: Thing
        in: body
        schema:
          $ref: '#/definitions/Thing'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Thing'
        401:
          description: Access Denied
        422:
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/Error'
  /HelloDBP/thing/{Id}:
    get:
      description: Returns details of a thing.
      operationId: readThing
      parameters:
      - name: Id
        in: path
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Thing'
        401:
          description: Access Denied
        422:
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/Error'
    patch:
      description: Updates a thing.
      operationId: updateThing
      parameters:
      - name: Id
        in: path
        required: true
        type: string
      - name: Thing
        in: body
        required: true
        schema:
          $ref: '#/definitions/Thing'
      responses:
        200:
          description: OK
        401:
          description: Access Denied
        422:
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: Deletes a thing.
      operationId: deleteThing
      parameters:
      - name: Id
        in: path
        required: true
        type: string
      responses:
        200:
          description: OK
        401:
          description: Access Denied
        422:
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/Error'
  /HelloDBP/thing/account/{Account}:
    get:
      description: Returns list of all things.
      operationId: listThingsForAccount
      parameters:
      - name: Account
        in: path
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Things'
        401:
          description: Access Denied
definitions:
  Things:
    type: object
    properties:
      Things:
        type: "array"
        items:
          $ref: "#/definitions/ThingBody"
  ThingBody:
    type: object
    properties:
      Id:
        type: string
      Name:
        type: string
      Health:
        type: integer
        format: int64
      Account:
        type: string
  Thing:
    type: object
    properties:
      Thing:
        $ref: "#/definitions/ThingBody"
  Error:
    type: object
    properties:
      message:
        type: string
